"""build_data.py — regenerate the embedded model data modules in src/data/.

Run once (or when upgrading a source dataset):

    py scripts/build_data.py <ccir_dir> <igrf14coeffs.txt> <ne_50m_land.geojson>

Sources (all public):
  * CCIR foF2 / M(3000)F2 numerical maps (ITU-R P.1239; as shipped with IRI):
      https://github.com/space-physics/iri2016/tree/main/src/iri2016/data/ccir  (ccir11.asc … ccir22.asc)
  * IGRF-14 coefficients:  https://www.ngdc.noaa.gov/IAGA/vmod/coeffs/igrf14coeffs.txt
  * Natural Earth 1:50m land: https://github.com/nvkelso/natural-earth-vector (geojson/ne_50m_land.geojson)

Outputs (plain ES modules so they load in the browser and in `node --test`):
  src/data/ccir.js      12 months × (foF2 13×76×2 + M3000 9×49×2) float32, base64
  src/data/igrf.js      IGRF-14 2025.0 main field + secular variation, n ≤ 13
  src/data/landmask.js  0.5° land/sea bitmask (row 0 = 89.75°N, col 0 = −179.75°E), base64
"""
import base64
import json
import os
import re
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', 'src', 'data')
NUM = re.compile(r'-?\d\.\d+E[+-]\d+')
CCIR_PER_MONTH = 13 * 76 * 2 + 9 * 49 * 2  # 2858


def b64(data: bytes) -> str:
    return base64.b64encode(data).decode('ascii')


def build_ccir(ccir_dir):
    vals = []
    for m in range(11, 23):
        with open(os.path.join(ccir_dir, f'ccir{m}.asc')) as fh:
            nums = [float(x) for x in NUM.findall(fh.read())]
        assert len(nums) >= CCIR_PER_MONTH, (m, len(nums))
        vals.extend(nums[:CCIR_PER_MONTH])
    raw = struct.pack(f'<{len(vals)}f', *vals)
    with open(os.path.join(OUT, 'ccir.js'), 'w', newline='\n', encoding='utf-8') as fh:
        fh.write('// Generated by scripts/build_data.py — do not edit.\n')
        fh.write('// CCIR (ITU-R P.1239) foF2 and M(3000)F2 numerical-map coefficients, 12 months.\n')
        fh.write('// Per month: foF2 F2[13][76][2] then M3000 FM3[9][49][2], Fortran column order,\n')
        fh.write('// little-endian float32. Index [.., .., 0] is R12 = 0, [.., .., 1] is R12 = 100.\n')
        fh.write(f'export const CCIR_PER_MONTH = {CCIR_PER_MONTH};\n')
        fh.write(f"export const CCIR_B64 = '{b64(raw)}';\n")


def build_igrf(path):
    g, h, sv_g, sv_h = {}, {}, {}, {}
    col = None
    with open(path) as fh:
        for line in fh:
            parts = line.split()
            if not parts:
                continue
            if parts[0] == 'g/h':
                col = parts.index('2025.0')
                continue
            if parts[0] in ('g', 'h') and col is not None:
                n, m = int(parts[1]), int(parts[2])
                main, sv = float(parts[col]), float(parts[-1])
                (g if parts[0] == 'g' else h)[(n, m)] = main
                (sv_g if parts[0] == 'g' else sv_h)[(n, m)] = sv
    nmax = max(n for n, _ in g)
    rows = []
    for n in range(1, nmax + 1):
        for m in range(0, n + 1):
            rows.append([n, m, g[(n, m)], h.get((n, m), 0.0), sv_g.get((n, m), 0.0), sv_h.get((n, m), 0.0)])
    with open(os.path.join(OUT, 'igrf.js'), 'w', newline='\n', encoding='utf-8') as fh:
        fh.write('// Generated by scripts/build_data.py — do not edit.\n')
        fh.write('// IGRF-14 Schmidt semi-normalised coefficients (nT) at epoch 2025.0 plus\n')
        fh.write('// secular variation (nT/yr). Rows: [n, m, g, h, dg, dh].\n')
        fh.write('export const IGRF_EPOCH = 2025.0;\n')
        fh.write(f'export const IGRF_NMAX = {nmax};\n')
        fh.write('export const IGRF = ' + json.dumps(rows, separators=(',', ':')) + ';\n')


def build_landmask(path, step=0.5):
    with open(path) as fh:
        gj = json.load(fh)
    nrow, ncol = int(180 / step), int(360 / step)
    crossings = [[] for _ in range(nrow)]  # x-intersections per scanline

    def rings():
        for f in gj['features']:
            geom = f['geometry']
            polys = geom['coordinates'] if geom['type'] == 'MultiPolygon' else [geom['coordinates']]
            for poly in polys:
                for ring in poly:
                    yield ring

    for ring in rings():
        for (x0, y0), (x1, y1) in zip(ring, ring[1:] + ring[:1]):
            if y0 == y1:
                continue
            lo, hi = min(y0, y1), max(y0, y1)
            # Scanline rows whose centre latitude lies in [lo, hi).
            r_first = int((90 - hi) / step - 0.5) - 1
            r_last = int((90 - lo) / step - 0.5) + 1
            for r in range(max(0, r_first), min(nrow, r_last + 1)):
                yc = 90 - (r + 0.5) * step
                if lo <= yc < hi:
                    t = (yc - y0) / (y1 - y0)
                    crossings[r].append(x0 + t * (x1 - x0))

    bits = bytearray((nrow * ncol + 7) // 8)
    land = 0
    for r in range(nrow):
        xs = sorted(crossings[r])
        for i in range(0, len(xs) - 1, 2):
            c0 = max(0, int((xs[i] + 180) / step + 0.5))
            c1 = min(ncol, int((xs[i + 1] + 180) / step + 0.5))
            for c in range(c0, c1):
                k = r * ncol + c
                bits[k >> 3] |= 1 << (k & 7)
                land += 1
    print(f'landmask: {land / (nrow * ncol):.1%} land')
    with open(os.path.join(OUT, 'landmask.js'), 'w', newline='\n', encoding='utf-8') as fh:
        fh.write('// Generated by scripts/build_data.py — do not edit.\n')
        fh.write('// Land (1) / sea (0) bitmask from Natural Earth 1:50m land polygons.\n')
        fh.write(f'// {nrow} rows × {ncol} cols at {step}°; row 0 centre = {90 - step / 2}°N, col 0 centre = {-180 + step / 2}°E.\n')
        fh.write('// Bit k = row*cols + col, LSB-first within each byte.\n')
        fh.write(f'export const LAND_STEP = {step};\n')
        fh.write(f'export const LAND_ROWS = {nrow};\n')
        fh.write(f'export const LAND_COLS = {ncol};\n')
        fh.write(f"export const LAND_B64 = '{b64(bytes(bits))}';\n")


if __name__ == '__main__':
    ccir_dir, igrf_path, land_path = sys.argv[1:4]
    os.makedirs(OUT, exist_ok=True)
    build_ccir(ccir_dir)
    build_igrf(igrf_path)
    build_landmask(land_path)
    print('wrote', os.path.normpath(OUT))
